# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "brainpickin_remote_auth"
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eli Purian"]
  s.date = "2013-04-29"
  s.description = "See the README."
  s.email = "eli@brainpickin.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "brainpickin_remote_auth.gemspec",
    "lib/brainpickin_remote_auth.rb",
    "spec/brainpickin_remote_auth_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/purian/brainpickin_remote_auth"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Helper for brainpickin Single Sign In/remote authentication"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.0"])
      s.add_development_dependency(%q<rspec>, [">= 2.6.0"])
    else
      s.add_dependency(%q<activesupport>, [">= 3.0.0"])
      s.add_dependency(%q<rspec>, [">= 2.6.0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 3.0.0"])
    s.add_dependency(%q<rspec>, [">= 2.6.0"])
  end
end

